name: Publish Docker
on:
  push:
    branches:
      - master
      - stable
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout branch
      uses: actions/checkout@master
    - name: Publish to Docker Hub
      uses: docker/build-push-action@v1.1.0
      with:
        repository: projectcaluma/caluma-demo
        tag_with_ref: true
        path: caluma-demo
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
