name: Publish Docker
on:
  push:
    branches:
      - stable
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout stable branch
      uses: actions/checkout@stable
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: projectcaluma/caluma-demo
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: caluma-demo
        dockerfile: Dockerfile
